import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Hamburger from "@/components/HamBurger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen grid grid-rows-[4rem_calc(100vh-4rem)]`}
      >
        <header className="relative text-xl font-bold text-center w-full p-4">
          <div className="absolute left-4 top-1/2 -translate-y-1/2">
            <Hamburger />
          </div>
          Changelog Markdown Editor
        </header>
        {children}
      </body>
    </html>
  );
}
